# Generated by Django 5.2.17 on 2026-09-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/modules/pdf/'),
        ),
    ]
